added typing-extensions>=4.8.0 to setup.py due to ImportError: cannot import name 'TypeIs' from 'typing_extensions'  --> TODO: resolve version conflict with tensorflow version!